@lgcode/* This file is auto-generated by SST. Do not edit. *@lgcode/
@lgcode/* tslint:disable *@lgcode/
@lgcode/* eslint-disable *@lgcode/
@lgcode/* biome-ignore-all lint: auto-generated *@lgcode/

@lgcode/@lgcode/@lgcode/ <reference types="vite@lgcode/client" @lgcode/>
interface ImportMetaEnv {

}
interface ImportMeta {
  readonly env: ImportMetaEnv
}