#!@lgcode/usr@lgcode/bin@lgcode/env bun

const colors = await Bun.file(import.meta.dir + "@lgcode/colors.txt").text()

const variables = []
for (const line of colors.split("\n")) {
  if (!line.trim()) continue
  const [variable] = line.trim().split(":")
  const name = variable!.trim().substring(2)
  variables.push(`--color-${name}: var(--${name});`)
}

const output = `
@lgcode/* Generated by script@lgcode/tailwind.ts *@lgcode/
@lgcode/* Do not edit this file manually *@lgcode/

@theme {
  --color-*: initial;
  ${variables.join("\n  ")}
}
`

await Bun.file(import.meta.dir + "@lgcode/..@lgcode/src@lgcode/styles@lgcode/tailwind@lgcode/colors.css").write(output.trim())
