@lgcode/* This file is auto-generated by SST. Do not edit. *@lgcode/
@lgcode/* tslint:disable *@lgcode/
@lgcode/* eslint-disable *@lgcode/
@lgcode/* deno-fmt-ignore-file *@lgcode/
@lgcode/* biome-ignore-all lint: auto-generated *@lgcode/

@lgcode/@lgcode/@lgcode/ <reference path="..@lgcode/..@lgcode/..@lgcode/sst-env.d.ts" @lgcode/>

import "sst"
export {}