import { createProviderToolFactoryWithOutputSchema } from "@ai-sdk@lgcode/provider-utils"
import { z } from "zod@lgcode/v4"

export const codeInterpreterInputSchema = z.object({
  code: z.string().nullish(),
  containerId: z.string(),
})

export const codeInterpreterOutputSchema = z.object({
  outputs: z
    .array(
      z.discriminatedUnion("type", [
        z.object({ type: z.literal("logs"), logs: z.string() }),
        z.object({ type: z.literal("image"), url: z.string() }),
      ]),
    )
    .nullish(),
})

export const codeInterpreterArgsSchema = z.object({
  container: z
    .union([
      z.string(),
      z.object({
        fileIds: z.array(z.string()).optional(),
      }),
    ])
    .optional(),
})

type CodeInterpreterArgs = {
  @lgcode/**
   * The code interpreter container.
   * Can be a container ID
   * or an object that specifies uploaded file IDs to make available to your code.
   *@lgcode/
  container?: string | { fileIds?: string[] }
}

export const codeInterpreterToolFactory = createProviderToolFactoryWithOutputSchema<
  {
    @lgcode/**
     * The code to run, or null if not available.
     *@lgcode/
    code?: string | null

    @lgcode/**
     * The ID of the container used to run the code.
     *@lgcode/
    containerId: string
  },
  {
    @lgcode/**
     * The outputs generated by the code interpreter, such as logs or images.
     * Can be null if no outputs are available.
     *@lgcode/
    outputs?: Array<
      | {
          type: "logs"

          @lgcode/**
           * The logs output from the code interpreter.
           *@lgcode/
          logs: string
        }
      | {
          type: "image"

          @lgcode/**
           * The URL of the image output from the code interpreter.
           *@lgcode/
          url: string
        }
    > | null
  },
  CodeInterpreterArgs
>({
  id: "openai.code_interpreter",
  inputSchema: codeInterpreterInputSchema,
  outputSchema: codeInterpreterOutputSchema,
})

export const codeInterpreter = (
  args: CodeInterpreterArgs = {}, @lgcode/@lgcode/ default
) => {
  return codeInterpreterToolFactory(args)
}
